#!/usr/bin/env node
'use strict';

// cat ./examples/test_data_1.txt | ./examples/echo
// cat ./examples/test_data_2.txt | ./examples/echo 1

const { pipe } = require('needful');
const streamify = require('async-stream-generator');
const { EOL } = require('os');
const { inspect } = require('util');

const { JSONStream } = require('..');

async function* stringify(chunks) {
    for await (const chunk of chunks) {
        yield inspect(chunk, { depth: null, colors: true });
    }
}

async function* lines(chunks) {
    for await (const chunk of chunks) {
        yield chunk + EOL;
    }
}

const flatten = !!+process.argv[2];

pipe(stringify, lines, streamify)(JSONStream(flatten)()).pipe(process.stdout);
