#!/usr/bin/env node
'use strict';

// cat ./examples/test_data_1.txt | ./examples/take 5
// cat ./examples/test_data_2.txt | ./examples/take 5 1

const {
    pipe,
    partialRight
} = require('needful');
const { inspect } = require('util');
const log = v => console.log(inspect(v, { depth: null, colors: true }))

const {
    Read,
    Take
} = require('..');

const count = +process.argv[2];
const flatten = !!+process.argv[3];

(async () => (await pipe(Read(flatten), Take(count))(process.stdin)).map(log))();
